### ISSUE TITLE
Problems with resetting the emoji reaction value to null

### ISSUE THREAD

**Issue by mmwoodfo** [IvanSotelo/VueFeedbackReaction#14]
Hey there,
Thanks for making this! There appears to be an issue with clearing the previously selected emoji  value & resetting the component so none of the emojis are selected.

**Issue details:**
After selecting an emoji in a v-dialog component and closing that component, when that component is re-opened in the same session the emoji that was selected stays selected even when setting variable bound to the v-model to null.

Here is the relevant code I have set up for this:
```vue
<template>
..
..
   <vue-feedback-reaction
      v-model="model.emojiReaction"
      :labels="['', '', '', '', '']" />
..
..
</template>

<script "lang=ts">
..
..
  closeDialog() {
    this.model.emojiReaction = null;
    this.model.comment = '';
    this.dialog = false;
  }
..
..
</script>
```

I would expect setting the v-model to null would reset the selected emoji, is this a legitimate issue or is there a different way to reset this component?
Thank you!

**Comment by jonorozcoc** [comment]
@mmwoodfo I just made a PR that solves your issue
