### ISSUE TITLE
Resize emojis for responsive design

### ISSUE THREAD

**Issue by jordanmcdougall** [IvanSotelo/VueFeedbackReaction#4]
First off, really enjoy what you've done :+1:

I was wondering if you're considering a way to scale the emoji's, maybe through a prop that can be passed into the element, eg:

```html
<vue-feedback-reaction width='10px'  height="auto" />
```
to control the size of each emoji

Would help with responsive web design if they could be resized, or even if they could inherit their size from a parent div.

**Comment by IvanSotelo** [comment]
@jordanmcdougall Thanks for the feedback! :)
