### ISSUE TITLE
Export emojis

### ISSUE THREAD

**Issue by guastallaigor** [IvanSotelo/VueFeedbackReaction#9]
Hello. I'm using this in a project and it's working properly. 
However, after the user selects the "feedback" and it's saved inside the database, I need to show the data somehow in our backoffice.
I was thinking of using the emojis inside a simple table for now, in a column called "Feedback Reaction" or something like that.
I know I can grab the emoji component or the images itself and put inside my project, but it'll be great in my opinion if this project exposes that as well.
If you consider that, I can try to work on it, and I will need a additional disable prop for a disabled state of each emoji or all emojis.
Thank you anyway 😄

**Comment by IvanSotelo** [comment]
@guastallaigor that'd be really awesome!
